COMPILER = g++
CFLAGS   = -g -w -MMD -MP -Wall -Wextra -Winit-self -Wno-unused-parameter -Wno-deprecated-declarations -Wfloat-equal -framework OpenGL -framework GLUT
LDFLAGS  = -framework GLUT -framework OpenGL
LIBS     =
INCLUDE  = -I../include
TARGET   = ../bin/$(shell basename `greadlink -f ..`)
OBJDIR   = ./obj
ifeq "$(strip $(OBJDIR))" ""
  OBJDIR = .
endif
SOURCES  = $(wildcard *.cpp)
OBJECTS  = $(addprefix $(OBJDIR)/, $(SOURCES:.cpp=.o))
DEPENDS  = $(OBJECTS:.o=.d)

$(TARGET): $(OBJECTS) $(LIBS)
	$(COMPILER) -o $@ $^ $(LDFLAGS)

$(OBJDIR)/%.o: %.cpp
	@[ -d $(OBJDIR) ] || mkdir -p $(OBJDIR)
	$(COMPILER) $(CFLAGS) $(INCLUDE) -o $@ -c $<

all: clean $(TARGET)

clean:
	rm -f $(OBJECTS) $(DEPENDS) $(TARGET)

-include $(DEPENDS)
